### ISSUE TITLE
Add Paragraph to Readme Describing `/create` Page Feature

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/standards#1]
Right now, we need to make a Readme that brings as many people as possible onto the page. Because of this, we need to write some paragraphs describing the features of the website.

For this paragraph, we need to write about the `/create` page. This page allows users to input their code on the left side of the page, and on the right side, the rendered standards document will be generated. This will allow users to quickly generate standards for the vault with a knowledge of how they will look when finished. 

If you would like to claim this issue– let me know!

Cheers,
Will

**Comment by hanzili** [comment]
Hello! I would like to contribute, can I claim this issue?

**Comment by hanzili** [comment]
I have added something to README but am denied for creating a branch for this repo

**Comment by William-McGonagle** [comment]
Fixed by @hanzili
