### ISSUE TITLE
Add a section below "Public standards, Made for all." showing the categories that we have

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/standards#12]
On the home page of the Vault, we have text that says "Public standards, Made for all." but we need more information on the landing page. Because of this, it would be great if we could get someone to add a section (on the home page) that shows all of the categories that we have. 

This section should be modeled after some of the sections on the [about website](https://about.fairfieldprogramming.org/).

Thank you,
Will

**Comment by pandeyprashant123-coder** [comment]
hey @William-McGonagle I didn't find the data for passing to the category page as props

**Comment by William-McGonagle** [comment]
Hey @pandeyprashant123-coder,

I can create that data ASAP- It'll be there in a few hours.

Cheers,
Will

**Comment by William-McGonagle** [comment]
Hey @pandeyprashant123-coder 

I believe that @hanzili just added in a categories page, so you could use some of the code from that to build the categories section on the main page. Also, you should probably limit the categories section to only showing like 8 or 10 categories at once.

**Comment by pandeyprashant123-coder** [comment]
sure @William-McGonagle  I will work on it

**Comment by pandeyprashant123-coder** [comment]
hey @William-McGonagle is `categories` a separate page or a component

**Comment by William-McGonagle** [comment]
Hey @pandeyprashant123-coder, I think a separate page– it should be in `src/pages/categories`

**Comment by pandeyprashant123-coder** [comment]
@William-McGonagle so, may I add it to the navigation bar list instead of the home page section

**Comment by William-McGonagle** [comment]
Oh I'm so sorry @pandeyprashant123-coder I misspoke- It should just be a component in the home page.

**Comment by William-McGonagle** [comment]
Nice work @pandeyprashant123-coder!
