### ISSUE TITLE
Get the Vault onto MadeWithTailwind

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/standards#15]
We need some more coverage/ popularity for this website, so we should try to get it onto showcase websites. One of these websites is [made with tailwind](https://madewithtailwindcss.com/), so just figure out how to get websites added, and submit this website to the process.

**Comment by hanzili** [comment]
<img width="362" alt="屏幕截图 2022-12-27 162830" src="https://user-images.githubusercontent.com/96609857/209724083-3e8cb7c0-1c62-47b2-b35a-aa8d78afcba9.png">
Submitted!

**Comment by William-McGonagle** [comment]
Thanks, @hanzili!
