### ISSUE TITLE
Redesign the 404 Page

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/standards#27]
The 404 Page, as found in `src/pages/404.js` looks really bad, so we should add some style to it.

If you would like to help with this issue, leave a comment below.

Cheers,
Will

**Comment by hanzili** [comment]
Can I work on this one?：）

**Comment by William-McGonagle** [comment]
Hey @hanzili– It looks like @pandeyprashant123-coder beat you to the punch! I can try to add more issues that need work though
