### ISSUE TITLE
Add Search Box to Standards Page, Allowing for Simple Discovery of Documents

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/standards#5]
Please add a search box to the standards page so that people can easily search through all of the standards. The search should be based on the document name, authors, and categories that the document has. 

If you want to claim this issue, please leave a comment below.

Thank you,
Will

**Comment by hanzili** [comment]
I want to claim this issue!

**Comment by William-McGonagle** [comment]
Sure @hanzili – I will assign it to you

**Comment by William-McGonagle** [comment]
Nice work on the search bar @hanzili– I've been checking it out and it's awesome!
