### ISSUE TITLE
Add a Categories Page

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/standards#6]
Right now, we have pages for each of the categories, but we just need a page where the user can choose which category they are looking for at the moment. This page will just have a grid of all the categories, a title, and a description. It should look like the other pages that follow a similar function.

If you want to be assigned to this, let me know by dropping a comment below.

Thank you,
Will

**Comment by hanzili** [comment]
Hello! I would like to contribute, can I claim this issue?

**Comment by William-McGonagle** [comment]
Sure– here you go @hanzili

**Comment by hanzili** [comment]
Thanks! May I ask what you mean by 

> we have pages for each of the categories

What categories do you refer to?

**Comment by William-McGonagle** [comment]
Hey @hanzili,

Using Gatsby's Deferred Static Generation, we create Category pages (it gets the categories by looking at each of the standards). These category pages are found at `/categories/[name here]`, such as [`/categories/file-format`](https://vault.fairfieldprogramming.org/categories/file-format). The code for each category page can be found in `src/templates/category`, and all the 'categories page' (the page we need to add) needs to do is link to each of the category pages generated (like `/categories/file-format`).

**Comment by William-McGonagle** [comment]
Nice work @hanzili!
