### ISSUE TITLE
Add in a Link to the Categories Page

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/standards#7]
Right now, a categories page (a page listing all of the categories) is in development. To allow users to access this page, we are going to need links on other pages to get people there. I'm not sure which other pages need to link to the category index, but use your best judgment (the [`/standards`](https://vault.fairfieldprogramming.org/standards/) page definitely should link to it).

If you would like to be assigned to this issue, please leave a comment below

Thank you,
Will

**Comment by pandeyprashant123-coder** [comment]
hello, I want to contribute to this project. May I claim this issue?

**Comment by William-McGonagle** [comment]
Sure, @pandeyprashant123-coder, I will assign you right now

**Comment by William-McGonagle** [comment]
Thanks @pandeyprashant123-coder!
