### ISSUE TITLE
Fix Some Bad SEO Information

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/standards#8]
At the moment, we have a lot of pages with incorrect SEO information on them. To fix this, please go through each page and make sure that the headings and paragraphs line up with the page titles and descriptions. Always trust the page information (headings and paragraphs) rather than the titles and descriptions, and if the page doesn't have a title or description, please add them in. 

If you want to do this, add a comment below and I will assign you.

Thank you,
Will

**Comment by navaneeth-dev** [comment]
Hi! I can contribute please assign me. So you want to me add proper SEO to pages inside `src/pages` right?

**Comment by William-McGonagle** [comment]
Yes @navaneeth-dev – all the stuff inside of the `src/pages`

**Comment by William-McGonagle** [comment]
Hey @navaneeth-dev,
I just merged in the pull request that you added– it all looks great. Let me know if you want to add in descriptions to each of the pages too, or if I should make a new issue for that (either is fine).

Thank you,
Will
